export enum RabbitMQ{
    UserQueue = 'users',
    PassengerQueue = 'passenger',
    FlightQueue = "flight"
}
export enum UserMSG{
    INSERTAR='CREAR_USUARIO',
    TODOS="TODOS_LOS_USUARIOS",
    UNO="UN_USUARIO",
    ACTUALIZAR="ACTUALIZAR_USUARIO",
    ELIMINAR="ELIMINAR_USUARIO",
    VALIDAR_USUARIO="VALIDAR_USUARIO",
}

export enum PassengerMSG{
    INSERTAR='CREAR_PASAJERO',
    TODOS="TODOS_LOS_PASAJEROS",
    UNO="UN_PASAJERO",
    ACTUALIZAR="ACTUALIZAR_PASAJERO",
    ELIMINAR="ELIMINAR_PASAJERO",
    VALIDAR_USUARIO="VALIDAR_PASAJERO",
}

export enum FlightMSG{
    INSERTAR='CREAR_VUELO',
    TODOS="TODOS_LOS_VUELOS",
    UNO="UN_VUELO",
    ACTUALIZAR="ACTUALIZAR_VUELO",
    ELIMINAR="ELIMINAR_VUELO",
    VALIDAR_USUARIO="VALIDAR_VUELO",
    AGREGAR_PASAGERO="AGREGAR_UN_PASAGERO_A_VUELO",
}